### ISSUE TITLE
aws-crt-python: can't resolve symbol / unknown dlopen() error

### ISSUE THREAD

**Issue by ssnyde** [aduskett/buildroot-aws-iot#1]
Hi,

I'm trying to use the aws-crt-python package and running into some challenges.  It's likely user error, I'm not sure.  I'm cross compiling for a Cortex-A5 using linux4sam/buildroot-at91 2021.10 release.

First, to build correctly, I had to comment out `cmdclass={'build_ext': awscrt_build_ext},` from setup.py in aws-crt-python.  It seemed setuptools was trying to build all the aws libraries but didn't understand the buildroot environment.  It thought it was on an x86 and was trying to link in x86 assembly code.  This seemed redundent because all these libraries were listed as dependencies in buildroot so were built outside of setuptools.

After commenting this out I got the build to work, but now I get a loader error at runtime.  

```
# python
Python 3.9.7 (default, May 14 2022, 13:46:36)
[GCC 10.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from awscrt import http

/usr/bin/python3.9: symbol 'aws_http_proxy_options_init_from_config': can't resolve symbol

/usr/bin/python3.9: symbol 'aws_http_proxy_new_socket_channel': can't resolve symbol

/usr/bin/python3.9: symbol 'aws_http_proxy_config_destroy': can't resolve symbol
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/awscrt/http.py", line 10, in <module>
ImportError: unknown dlopen() error
```

If you can provide any advice, it would be much appreciated.

**Comment by aduskett** [comment]
ooo, I'll take a look right now! What branch are you using? Do you have a defconfig I can use?

**Comment by aduskett** [comment]
Hello, I was able to reproduce the issue and added a new patch.
In addition, websockets is required from the mqtt package, so I changed aws/package/aws-crt-python/Config.in to select mqtt websockets! Thanks again for the issue! 

Adam

**Comment by ssnyde** [comment]
Thanks for adding the patch.  Now I don't have to edit anything and it all build straight away.

However, the same runtime issue is happening.  [Here](https://github.com/ssnyde/buildroot-at91/blob/master-bertad2/configs/acme-bertad2_defconfig) is my defconfig.  If you want to try repro'ing directly, you could pull that github repo, branch master-bertad2.  I'd much appreciate any help you can lend.

**Comment by ssnyde** [comment]
Ok, so I tried changing from uclibc to glibc, and the problem is gone now.  I have no idea what's going on here.  Interested in your thoughts.

**Comment by aduskett** [comment]
hmmm, quite interesting. It's probably a macro in uclibc that isn't defined. I will investigate further. I'm glad you were able to get it working though! I'll let you know later this week!
